springdoc:
  swagger-ui:
    path: "swagger-ui"
server:
  port: 8080
app:
  test: 1234
  scheduler:
    interval: 10000
github:
  url: "https://api.github.com/repos/"
stackoverflow:
  url: "https://api.stackexchange.com/2.3/questions/"
  mandatory-request-params: "?order=desc&sort=activity&site=stackoverflow"
webclient:
  timeout: 1000
bot:
  url:
    base: http://localhost:8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/scrapper
    username: postgres
    password: postgres



