springdoc:
  swagger-ui:
    path: "swagger-ui"
server:
  port: 8080
app:
  test: 1234
  scheduler:
    interval: 10000
github:
  url: "https://api.github.com/repos/"
stackoverflow:
  url: "https://api.stackexchange.com/2.3/questions/"
  mandatory-request-params: "?order=desc&sort=activity&site=stackoverflow"
webclient:
  timeout: 1000
