springdoc:
  swagger-ui:
    path: "swagger-ui"
server:
  port: 8081
app:
  test: 1234
  bot:
    name: "first_bot"
    token: ${env.TOKEN}
  client:
    baseUrl: "http://localhost:8080/"
  rabbit-queue:
    exchange-name: scrapper-bot-exchange
    queue-name: scrapper-bot-queue
    routing-key: scrapper-bot-key
webclient:
  timeout: 1000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
