springdoc:
  swagger-ui:
    path: "swagger-ui"
server:
  port: 8080
app:
  test: 1234
  bot:
    name: "first_bot"
    token: ${TELEGRAM_TOKEN}
  client:
    baseUrl: "http://localhost:8080/"
webclient:
  timeout: 1000