/*
 * This file is generated by jOOQ.
 */
package com.example.scrapper.domain.jooq.tables;


import com.example.scrapper.domain.jooq.Keys;
import com.example.scrapper.domain.jooq.Public;
import com.example.scrapper.domain.jooq.tables.records.TgChatRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TgChat extends TableImpl<TgChatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tg_chat</code>
     */
    public static final TgChat TG_CHAT = new TgChat();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TgChatRecord> getRecordType() {
        return TgChatRecord.class;
    }

    /**
     * The column <code>public.tg_chat.id</code>.
     */
    public final TableField<TgChatRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    private TgChat(Name alias, Table<TgChatRecord> aliased) {
        this(alias, aliased, null);
    }

    private TgChat(Name alias, Table<TgChatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tg_chat</code> table reference
     */
    public TgChat(String alias) {
        this(DSL.name(alias), TG_CHAT);
    }

    /**
     * Create an aliased <code>public.tg_chat</code> table reference
     */
    public TgChat(Name alias) {
        this(alias, TG_CHAT);
    }

    /**
     * Create a <code>public.tg_chat</code> table reference
     */
    public TgChat() {
        this(DSL.name("tg_chat"), null);
    }

    public <O extends Record> TgChat(Table<O> child, ForeignKey<O, TgChatRecord> key) {
        super(child, key, TG_CHAT);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<TgChatRecord> getPrimaryKey() {
        return Keys.TG_CHAT_PKEY;
    }

    @Override
    @NotNull
    public TgChat as(String alias) {
        return new TgChat(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public TgChat as(Name alias) {
        return new TgChat(alias, this);
    }

    @Override
    @NotNull
    public TgChat as(Table<?> alias) {
        return new TgChat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgChat rename(String name) {
        return new TgChat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgChat rename(Name name) {
        return new TgChat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgChat rename(Table<?> name) {
        return new TgChat(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
