/*
 * This file is generated by jOOQ.
 */
package com.example.scrapper.domain.jooq.tables.records;


import com.example.scrapper.domain.jooq.tables.TgChat;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TgChatRecord extends UpdatableRecordImpl<TgChatRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tg_chat.id</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tg_chat.id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return TgChat.TG_CHAT.ID;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public TgChatRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public TgChatRecord values(@NotNull Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TgChatRecord
     */
    public TgChatRecord() {
        super(TgChat.TG_CHAT);
    }

    /**
     * Create a detached, initialised TgChatRecord
     */
    @ConstructorProperties({ "id" })
    public TgChatRecord(@NotNull Long id) {
        super(TgChat.TG_CHAT);

        setId(id);
    }

    /**
     * Create a detached, initialised TgChatRecord
     */
    public TgChatRecord(com.example.scrapper.domain.jooq.tables.pojos.TgChat value) {
        super(TgChat.TG_CHAT);

        if (value != null) {
            setId(value.getId());
        }
    }
}
