name: Bot CI

on:
  push:
    paths:
      - 'bot/**'
      - 'link-parser/**'
      - 'pom.xml'
      - '.github/workflows/bot.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Jar
        run: mvn package -pl bot -am

      - name: Build Image
        run: cd project && docker build --file scrapper.Dockerfile -t ghcr.io/pro100bat9/scrapper:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: docker push ghcr.io/pro100bat9/scrapper:latest
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run checker
        run: mvn -pl bot -am checkstyle:check
