name: Scrapper CI

on:
  push:
    paths:
      - 'scrapper/**'
      - 'link-parser/**'
      - 'pom.xml'
      - '.github/workflows/scrapper.yml'
      - 'scrapper-jooq/**'
      - 'migrations'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build JOOQ
        run: mvn package -pl scrapper-jooq -am

      - name: Build Jar
        run: mvn package -pl scrapper -am

      - name: Build Image
        run: docker build -t ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }} . -f scrapper/Dockerfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run checker
        run: mvn -pl scrapper -am checkstyle:check


